sonar.projectKey=devops-frontend
sonar.projectName=devops-frontend
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/environments/**
sonar.typescript.tsconfigPath=tsconfig.json
